### ISSUE TITLE
Length is not verified.

### ISSUE THREAD

**Issue by landeeyo** [vkomulai/finnish-ssn#1]
As far as I know maximum length of Finnish SSN is 11 characters. Currently the library doesn't verify the length of the SNN.

If we take for example this test, it will return true. And it is okay.

`FinnishSSN.validate('010114A173M')`

But if we append anything at the end it will still validate it as correct, while it's not.

`FinnishSSN.validate('010114A173M89edyhasd')`

**Comment by vkomulai** [comment]
Thanks for reporting this bug landeeyo! It is now fixed with tighter regex. Version 1.0.2 availaible in npm.
