### ISSUE TITLE
Upcomming reform of personal identity code

### ISSUE THREAD

**Issue by ChuckBorris33** [vkomulai/finnish-ssn#19]
It's possible that from 1.1.2023 there will be new symbols to represent 20th and 21st century.
Full proposal: [https://dvv.fi/en/reform-of-personal-identity-code](https://dvv.fi/en/reform-of-personal-identity-code)

Important part:

> The new punctuation marks are:
>     For those born in the 2000s: B, C, D, E and F, from letter B to replace current letter A 
>     For those born in the 20th century, Y, X, W, V, U, from the letter Y to replace the current symbol -.

These changes are did not  pass through parliament yet but it would be nice if this library is ready for them.

**Comment by pkoivisto** [comment]
And the above changes did in fact take effect on 1 January 2023: https://finlex.fi/fi/laki/ajantasa/2010/20100128#L1P2

Any chance of getting #20 merged soonish?

**Comment by danshaman05** [comment]
> Any chance of getting #20 merged soonish?

Until then, you can use my fork. https://github.com/danshaman05/finnish-ssn-2

**Comment by sebazai** [comment]
Released version 2.1.0 with the necessary changes.
