### ISSUE TITLE
Wrong SSN validation(

### ISSUE THREAD

**Issue by zgrybus** [vkomulai/finnish-ssn#9]
Hello! I have probably found the small bug in your library.
When I type this SSN ```000931-5511```, your library returns```{ valid: true }```, but as i know it's not valid ssn.

It's probably, because you allow to type:
1) ```00``` as a day
2) ```00``` as a month

As i can see, this bug is caused by this [regex](https://github.com/vkomulai/finnish-ssn/blob/master/src/finnish-ssn.ts#L132), which allows to enter such data.

**Confirmation of my words:**
![image](https://user-images.githubusercontent.com/17850996/59261000-f225ca00-8c3c-11e9-930d-b2162a144db6.png)

**Comment by zgrybus** [comment]
Have you deployed new version into npm?

Version 2.0.2 on npm still has this regex
```
  const SSN_REGEX = /^[0-3][\d][0-1][0-9][0-9]{2}[+\-A][\d]{3}[\dA-Z]$/;
```

so this SSN ```000931-5511``` is still valid.. :(

**Comment by vkomulai** [comment]
Yes, this is now deployed

**Comment by zgrybus** [comment]
Hello guys. Next problem, after npm install finnish-ssn, I am getting cannot find module 'finnish-ssn';

Folder finnish-ssn is in node_modules

![image](https://user-images.githubusercontent.com/17850996/60002496-0ae4a580-9669-11e9-962a-53d65e446294.png)

**Comment by sathiyaanbu** [comment]
@vkomulai I updated this library from 1.2.0 -> 2.0.4 after that it's not working in ie11. Any leads to this issue?
Another bug in that it does't validate for 2020 birth dates.
